import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Firebase configuration for the NGO Education Platform.
///
/// Generated by `flutterfire configure` for project `smarteducationanalyticssystem`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return web; // Windows uses web config
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkRiebjSeMF2Han4VyZGBoJb72pJSubZk',
    appId: '1:61191392694:web:1b8a80e6b6f9e9445a0517',
    messagingSenderId: '61191392694',
    projectId: 'smarteducationanalyticssystem',
    authDomain: 'smarteducationanalyticssystem.firebaseapp.com',
    storageBucket: 'smarteducationanalyticssystem.firebasestorage.app',
    measurementId: 'G-W1WBQLV1HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb47RUyanqSOkAbpvcCgcoPNFAkzoFsWY',
    appId: '1:61191392694:android:c39d1ef68f7d10055a0517',
    messagingSenderId: '61191392694',
    projectId: 'smarteducationanalyticssystem',
    storageBucket: 'smarteducationanalyticssystem.firebasestorage.app',
  );

  // iOS not yet configured — run `flutterfire configure` with --platforms=ios when needed
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkRiebjSeMF2Han4VyZGBoJb72pJSubZk',
    appId: '1:61191392694:web:1b8a80e6b6f9e9445a0517',
    messagingSenderId: '61191392694',
    projectId: 'smarteducationanalyticssystem',
    storageBucket: 'smarteducationanalyticssystem.firebasestorage.app',
  );
}